"""add category translations

Revision ID: 40fc913236e1
Revises: 871c50e31209
Create Date: 2026-04-22 02:43:18.703945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40fc913236e1'
down_revision = '871c50e31209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_tr', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name_ka', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('name_ka')
        batch_op.drop_column('name_tr')

    # ### end Alembic commands ###
