"""update bridge to productcategory

Revision ID: 871c50e31209
Revises: 0a346269b93b
Create Date: 2026-04-17 15:40:54.574780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871c50e31209'
down_revision = '0a346269b93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_category'), type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_product_category'), 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
