"""added role to user

Revision ID: 976fae401056
Revises: dc029b2c8a00
Create Date: 2026-02-16 13:56:11.455303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976fae401056'
down_revision = 'dc029b2c8a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=24), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
